name: tests
on: pull_request
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: install Eismassim
          run: mvn install:install-file -Dfile=${{ hashFiles('**/src/java/resources/eismassim-4.4-jar-with-dependencies }} -DgroupId=massim -DartifactId=eismassim -Dversion=4.4 -Dpackaging=jar
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
